name: NovaMobsX
main: com.pikycz.novamobs.NovaMobsX
version: "1.0"
api: ["1.0.0"]

load: STARTUP
author: PikyCZ
website: https://github.com/PikyCZ/NovaMobsX

commands:
  mob:
    description: Spawn a simple mob to the player, that is using this command
    aliases: ["mob"]
    usage: /mob
    permission: novamobs.mob  
    
permissions:
  novamobs.mob:
    description: ""
    default: op
    
